### ISSUE TITLE
Selective processing and uploading of articles and collections mentioned in the command-line argument

### ISSUE THREAD

**Issue by pavithraarizona** [UAL-RE/ReBACH#27]
Currently, the ReBACH software processes and upload all articles and collections on Figshare, which can be time-consuming. With this enhancement, the software will be able to selectively process and upload articles and collections based on their provided IDs.

It is crucial to complete Enhancement #44 before implementing this enhancement because the former handles the extraction of article and collection IDs from command line argument. This enhancement handles processing and uploading of extracted article and collection Ids

In addition to this enhancement, the following new features have been added:

1. Calculation of required space when article IDs are explicitly provided.
2. Counting and display of articles for which curation folders exist and do not exist.

**Comment by zoidy** [comment]
Implementation notes

- [ ] Filtering of articles needs to consider the free space 
- [ ] README.md needs to be updated to include instructions on how to use the new functionality
