### ISSUE TITLE
Check if a preservation archive exists in preservation storage if matching is unsuccessful

### ISSUE THREAD

**Issue by zoidy** [UAL-RE/ReBACH#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Currently, if a dataset in figshare does not have a corresponding curation folder, a warning is returned. There could be several reasons why the curation folder doesn't exist

1. The curation folder was inadvertently deleted or renamed. The existing warning will catch this.
2. The item is already preserved in storage therefore the folder was deleted. If the item is already preserved, this is not a warning/error condition.

Therefore for 2., we can skip showing a warning if the item is already preserved. Note, this will require reconciling the functionality with #61

**Comment by HafeezOJ** [comment]
#102  is a prerequisite to this issue
